package org.accounting.forms.partials;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import org.accounting.database.models.Base;
import org.accounting.database.models.Role;
import org.accounting.database.models.User;
import org.accounting.forms.RolesForm;
import org.accounting.forms.models.comboboxmodels.MainComboBoxModel;
import org.accounting.forms.models.comboboxmodels.RoleComboBoxModel;
import org.accounting.user.CurrentUser;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class UserFields extends JPanel implements ActionListener {
    public JLabel labelEmail;
    public JTextField textFieldEmail;
    public JLabel labelPassword;
    public JTextField textFieldPassword;
    public JLabel labelRole;
    public JComboBox comboBoxRoles;
    public JButton showRolesFormButton;
    public JPanel panel;
    private JPanel userFieldsPanel;
    public MainComboBoxModel roleModel;

    public UserFields() {
        if (!(CurrentUser.getUser().getRole().isAdmin())) {
            labelRole.setVisible(false);
            comboBoxRoles.setVisible(false);
            showRolesFormButton.setVisible(false);
        }

        roleModel = new RoleComboBoxModel();
        addItemComboBoxRole();
        comboBoxRoles.setModel(roleModel);

        showRolesFormButton.addActionListener(this);
    }

    private void addItemComboBoxRole() {
        roleModel.removeAllElements();
        Role.getAll().forEach(roleModel::addRecord);
    }

    public User buildUser() {
        Role role = new Role();
        User user = new User();
        user.setEmail(textFieldEmail.getText());
        user.setPassword(textFieldPassword.getText());
        if (roleModel.getSelection().map(Base::getId).orElse(0) == 0) {
            user.setRoleId(role.getRoleIdByLookupCode());
            return user;
        }
        user.setRoleId(roleModel.getSelection().map(Base::getId).get());
        return user;
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        switch (e.getActionCommand()) {
            case "addRoles":
                new RolesForm().setVisible(true);
                addItemComboBoxRole();
                break;
        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        userFieldsPanel = new JPanel();
        userFieldsPanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel = new JPanel();
        panel.setLayout(new GridLayoutManager(6, 2, new Insets(0, 0, 0, 0), -1, -1));
        userFieldsPanel.add(panel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        labelEmail = new JLabel();
        labelEmail.setText("Email");
        panel.add(labelEmail, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(32, 26), null, 0, false));
        textFieldEmail = new JTextField();
        panel.add(textFieldEmail, new GridConstraints(1, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        labelPassword = new JLabel();
        labelPassword.setText("Password");
        panel.add(labelPassword, new GridConstraints(2, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        textFieldPassword = new JTextField();
        panel.add(textFieldPassword, new GridConstraints(3, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        labelRole = new JLabel();
        labelRole.setText("Role");
        panel.add(labelRole, new GridConstraints(4, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        comboBoxRoles = new JComboBox();
        panel.add(comboBoxRoles, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        showRolesFormButton = new JButton();
        showRolesFormButton.setActionCommand("addRoles");
        showRolesFormButton.setHorizontalTextPosition(11);
        showRolesFormButton.setMargin(new Insets(0, 0, 0, 0));
        showRolesFormButton.setText("...");
        showRolesFormButton.setToolTipText("");
        showRolesFormButton.setVerticalTextPosition(0);
        panel.add(showRolesFormButton, new GridConstraints(5, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return userFieldsPanel;
    }
}
