package org.accounting.forms.workbooks;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;

public class WorkBooksForm extends JDialog {
    private JTabbedPane tabbedPane;

    public WorkBooksForm() {
        createWorkBooksForm();
    }

    private void createWorkBooksForm() {
        setContentPane(tabbedPane);
        setSize(900, 600);
        setMinimumSize(new Dimension(900, 300));
        setLocationRelativeTo(null);
        setTitle("Work Books");
        setModalityType(ModalityType.APPLICATION_MODAL);

        tabbedPane.add("Suppliers", new SuppliersForm().getPanel());
        tabbedPane.add("Workers", new WorkersForms().getPanel());
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        tabbedPane = new JTabbedPane();
        tabbedPane.setTabLayoutPolicy(0);
        panel1.add(tabbedPane, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, new Dimension(400, 300), null, null, 1, false));
    }
}
